### ISSUE TITLE
Plugin Conflict with Themify and DragOn Order

### ISSUE THREAD

**Issue by NovaViper** [jneilliii/OctoPrint-ConsolidateTempControl#5]
I notice that the plugin seems to cause major conflicts with other tabs where every other tab is shifted over. I tried to use Themify to fix the issue but it doesn't seem to fix it at all. Here are the settings for Themify 
![image](https://user-images.githubusercontent.com/7191115/72688586-5a3f6700-3ace-11ea-995a-aa8bddeff00f.png)

ConslidateTempControl disabled result: 
![image](https://user-images.githubusercontent.com/7191115/72688593-74794500-3ace-11ea-94a9-7f25fc365a43.png)

ConslidateTempControl enabled result: 
![image](https://user-images.githubusercontent.com/7191115/72688596-80fd9d80-3ace-11ea-9a56-f3418cc40232.png)

**Comment by jneilliii** [comment]
This is actually a conflict with Octolapse specifically, I'll look into resolving that.  Octolapse's tab must be doing something similar to this one and making the width larger than the default octoprint's tabs' widths.

**Comment by NovaViper** [comment]
This seems to happen across all other tabs, not just Octolapse. Some of the changes I disabled in my forked version of the plugin seems to fix the issues

**Comment by jneilliii** [comment]
If I remember correctly the issues I was running into by not shrinking the tab content back down was with the gcode viewer tab specifically.

**Comment by NovaViper** [comment]
@jneilliii Are the CSS mods that deletes both span8 and span4 needed? In my fork, I commented those lines out and it seemed to fix everything

**Comment by NovaViper** [comment]
The tweak also made plugins like the DragOn order plugin's ability to drag the sidebar order work again too. It's something with those specific CSS elements that seems to effectively break everything

**Comment by jneilliii** [comment]
Does your gcode viewer tab look right and function properly with your version?

**Comment by NovaViper** [comment]
@jneilliii Yeah

**Comment by jneilliii** [comment]
Ok, I'll test your fork in a bit.

**Comment by jneilliii** [comment]
So with your fork I'm seeing the same issue that I saw before.  See screenshot below.

![image](https://user-images.githubusercontent.com/5249455/59724945-c6d14b00-91f9-11e9-8424-f9acc8fe43d2.png)

I'm unsure if the issue doesn't happen for you because of Themify or one of the other plugin's that I have installed is causing it to do it. That's why I was wrapping those other tabs in a smaller div.

FYI...once you've ordered everything you want with DragonOrder you don't have to keep it enabled, so you could in theory disable this one, move everything the way you want it, then disable DragonOrder and re-enable this one.

**Comment by NovaViper** [comment]
Oh *that* issue.. hm.. I haven't a clue why it's doing that. It actually does do that on my setup, I've just ignored it though. But it's something with actually deleting span8 and span4 that causes every other tab to break and not respond to Themify's changes

**Comment by elminster** [comment]
I was about to raise an issue and saw this, I hit the same problem, installing the plugin made all the screen layout go horrible, with the side panel appearing above the main panel. Disabling it sorted the issue. I am also using Themify to 'stretch' things to use all my screen area. Looks like you are already onto the issue, if you need another testers to try any fixes I happy to try.

**Comment by jneilliii** [comment]
If you use the vertical layout mode does it still do it?

**Comment by elminster** [comment]
I re-enabled it, updated to 0.17 and changed to vertical, and that fixed it thanks. (although horizontal display would be nice)

Edit: Forgot to add above I also have DragOn Enabled as well.

**Comment by jneilliii** [comment]
I think I've resolved this issue to the best possible option in the commit above, to be released in the next version. For Themeify I now no longer change the class names of the sidebar, which will result in a wide sidebar since it's not getting adjusted anymore. You'll have to tweak your Themeify advanced options accordingly. For DragonOrder I recommend the following approach. With the DrgonOrder plugin enabled, adjust the positions of where you want things and once you're happy with the positions disable that plugin. Your ordering will remain as that is part of OctoPrint's core functionality, I'm just providing a method within the UI to change those settings. 

If you'd like to test this out prior to official release that would be greatly appreciated. Copy/Paste the URL below into Plugin Manager > Get More > ...from URL and clicking Install.

```
https://github.com/jneilliii/OctoPrint-ConsolidateTempControl/archive/0.1.8rc2.zip
```
